# Generated by Django 4.2.7 on 2025-11-27 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(max_length=50, unique=True, verbose_name='設備ID')),
                ('name', models.CharField(max_length=100, verbose_name='設備名稱')),
                ('status', models.CharField(choices=[('running', '運轉中'), ('stopped', '停止'), ('maintenance', '維護中'), ('error', '故障')], max_length=20, verbose_name='狀態')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='溫度')),
                ('vibration', models.FloatField(blank=True, null=True, verbose_name='震動')),
                ('power_consumption', models.FloatField(blank=True, null=True, verbose_name='能耗')),
            ],
            options={
                'verbose_name': '設備',
                'verbose_name_plural': '設備',
            },
        ),
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('line_id', models.CharField(max_length=50, verbose_name='生產線ID')),
                ('output', models.IntegerField(verbose_name='產量')),
                ('yield_rate', models.FloatField(verbose_name='良率')),
            ],
            options={
                'verbose_name': '生產資料',
                'verbose_name_plural': '生產資料',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', '資訊'), ('warning', '警告'), ('error', '錯誤'), ('critical', '嚴重')], max_length=20, verbose_name='等級')),
                ('message', models.TextField(verbose_name='訊息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解決時間')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.equipment', verbose_name='設備')),
            ],
            options={
                'verbose_name': '警報',
                'verbose_name_plural': '警報',
                'ordering': ['-created_at'],
            },
        ),
    ]
